{% set name = "transifex-client" %}
{% set version = "0.14.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/transifex-client-{{ version }}.tar.gz
  sha256: 11dc95cefe90ebf0cef3749c8c7d85b9d389c05bd0e3389bf117685df562bd5c

build:
  number: 0
  noarch: python
  entry_points:
    - tx=txclib.cmdline:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python <3.10
  run:
    - gitpython <4.0.0
    - python <3.10
    - python-slugify <5.0.0
    - requests >=2.19.1,<3.0.0
    - six <2.0.0
    - urllib3 >=1.24.2,<2.0.0

test:
  imports:
    - txclib
  commands:
    - pip check
    - tx --version
  requires:
    - pip
    - git

about:
  home: https://www.transifex.com
  summary: A command line interface for Transifex
  license: GPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
